version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/fraud_detection
    depends_on:
      - mongo
      - ml-api

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  ml-api:
    build:
      context: ./ml-api
    ports:
      - "5001:5000"
    volumes:
      - ./ml-api:/app

volumes:
  mongo_data: